# Generated by Django 5.1.1 on 2024-09-15 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('installing_time_in_mins', models.IntegerField()),
                ('size_in_bytes', models.IntegerField()),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('logo_file_path', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'software',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DELETED', 'Deleted'), ('FORMED', 'Formed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('host', models.CharField(max_length=255)),
                ('total_installing_time_in_min', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='SoftwareInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_software.request')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_software.software')),
            ],
            options={
                'db_table': 'software_in_request',
                'unique_together': {('request', 'software')},
            },
        ),
    ]
