# Generated by Django 5.1.1 on 2024-09-22 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_software', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='InstallSoftwareRequest',
        ),
        migrations.AlterModelTable(
            name='installsoftwarerequest',
            table='install_software_requests',
        ),
    ]
