# Generated by Django 5.1.1 on 2024-11-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_software', '0002_rename_request_installsoftwarerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='logo_file_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
